Update build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,22 @@
 #!/usr/bin/env bash
 
+for i in genisoimage mkisofs; do
+	if [ -e `command -v ${i}` ]; then
+		IMAGER="${i}"
+		break
+	else
+		echo "Please install ${i}"
+		fail="true"
+	fi
+done
+[ ${fail}="true" ] && echo "Please install above apps to run this tool" && exit 1
+fail=""
+for i in mksquashfs cpio gzip sed bash; do
+	[ ! -e `command -v ${i}` ] && echo "Please install ${i}" && fail="true"
+done
+[ ${fail}="true" ] && echo "Please install above apps to run this installer" && exit 1
+unset fail
+
 cp -raf config .config
 for i in "`find /boot -name \"vmlinuz*\" -o -name \"*kernel*\"`"; do
 	if [ `echo ${i} | wc -l` -eq 2 ]; then
@@ -52,7 +69,7 @@ sed -i -r "s/__DISTRO__/${DISTRO}/" ${BOOT}/syslinux.cfg
 cp -raf ${KERNEL} ${BOOT}/vmlinuz
 cd ${DATA}
 timedate="`date +"%d-%m-%Y"`"
-${MKISOFS} -o "/${DISTRO}-${timedate}.iso" -v -J -R -D -A ${DISTRO} -V ${DISTRO} -no-emul-boot -boot-info-table -boot-load-size 4 -b isolinux.bin -c isolinux.boot . || exit 1
+${MKISOFS} -o /${DISTRO}-${timedate}.iso -J -R -D -A ${DISTRO} -V ${DISTRO} -no-emul-boot -boot-info-table -boot-load-size 4 -b isolinux.bin -c isolinux.boot .
 if command -v isohybrid >/dev/null; then
 	isohybrid "/${DISTRO}-${timedate}.iso"
 fi
