Update build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,7 +2,7 @@
 
 IMAGER=$(command -v mkisofs)
 [ "${IMAGER}" = "" ] && IMAGER=$(command -v genisoimage)
-[ "${IMAGER}" = "" ] && echo "Cannot found mkisofs or genisoimage" && exit 1
+[ "${IMAGER}" = "" ] && echo "Can not found mkisofs or genisoimage" && exit 1
 for i in mksquashfs cpio gzip sed bash; do
 	if [ ! -e `command -v ${i}` ]; then
 		echo "Please install ${i} app to run this tool"
